import Footer from "./components/footer";
import Header from "./components/header";
import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl" >
      <body
        className=" max-w-[1512px] mx-auto  font-iran bg-[#FBFBFB]"
      >
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
